DROP TABLE IF EXISTS `client_submit`;
CREATE TABLE `client_submit` (
  `msgtype` decimal(1,0) default NULL,
  `needreport` decimal(1,0) default NULL,
  `priority` decimal(1,0) default NULL,
  `serviceid` varchar(10) default NULL,
  `feetype` varchar(2) default NULL,
  `fixedfee` varchar(6) default NULL,
  `feecode` char(10) default NULL,
  `msgformat` decimal(2,0) default NULL,
  `validtime` varchar(17) default NULL,
  `attime` varchar(17) default NULL,
  `srctermId` varchar(21) default NULL,
  `chargetermId` varchar(21) default NULL,
  `desttermidcount` int(11) default NULL,
  `desttermid` varchar(21) default NULL,
  `msglength` int(11) default NULL,
  `msgcontent` varchar(252) default NULL,
  `reserve` varchar(8) default NULL,
  `state` decimal(3,0) default NULL,
  `msgid` varchar(65) default NULL,
  `timewindowid` decimal(2,0) default NULL,
  `instructionid` decimal(10,0) default NULL,
  `trafficid` decimal(2,0) default NULL,
  `msgMode` decimal(1,0) default NULL,
  `id` varchar(255) NOT NULL,
  `create_date` datetime default NULL,
  `modify_date` datetime default NULL,
  `sequence_id` int(11) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `client_deliver`;
CREATE TABLE `client_deliver` (
  `deliver_id` bigint(18) default NULL,
  `msgid` varchar(40) default NULL,
  `msgformat` decimal(2,0) default NULL,
  `srctermid` varchar(21) default NULL,
  `recvtime` varchar(14) default NULL,
  `desttermid` varchar(21) default NULL,
  `msglength` decimal(3,0) default NULL,
  `msgcontent` varchar(252) default NULL,
  `reserve` varchar(10) default NULL,
  `state` decimal(1,0) default NULL,
  `msgMode` decimal(1,0) default NULL,
  `id` varchar(255) NOT NULL,
  `create_date` datetime default NULL,
  `modify_date` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;